//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Infoes = new HashSet<Info>();
        }
    
        public int Id { get; set; }
        public string Brand { get; set; }
        public string ItemName { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Fit { get; set; }
        public string Material { get; set; }
        public string Notes { get; set; }
        public string Image { get; set; }
        public string Careinstructions { get; set; }
        public string StoreItemNumber { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CategoriesId { get; set; }
        public Nullable<int> Userid { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Info> Infoes { get; set; }
        public virtual User User { get; set; }
    }
}
